server:
  port: 6083
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15001167619/spring-cloud/     # 配置git仓库的地址
          search-paths: config                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: username                                        # git仓库的账号
          password: password.                                    # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6080/eureka/   # 注册中心eurka地址
