spring:
  application:
    name: spring-cloud-consumer-hystrix
  profiles:
      active: dev
server:
  port: 6084
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6080/eureka/


