---
spring:
  application:
    name: spring-cloud-cluster-eureka
  profiles: master
server:
  port: 8000

security:
  basic:
    enabled: true #开启认证
  user:
    name: master
    password: master

eureka:
  instance:
    hostname: master
  client:
    serviceUrl:
      defaultZone: http://bizone:8001/eureka/,http://biztwo:8002/eureka/
---
spring:
  application:
    name: spring-cloud-cluster-eureka
  profiles: bizone
server:
  port: 8001

security:
  basic:
    enabled: true #开启认证
  user:
    name: bizone
    password: bizone

eureka:
  instance:
    hostname: bizone
  client:
    serviceUrl:
      defaultZone: http://master:8000/eureka/,http://biztwo:8002/eureka/
---
spring:
  application:
    name: spring-cloud-cluster-eureka
  profiles: biztwo
server:
  port: 8002

security:
  basic:
    enabled: true #开启认证
  user:
    name: biztwo
    password: biztwo

eureka:
  instance:
    hostname: biztwo
  client:
    serviceUrl:
      defaultZone: http://master:8000/eureka/,http://bizone:8001/eureka/
